spring.application.name=SmartRestaurant
spring.datasource.url=jdbc:mysql://localhost:3306/smart_restaurant?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
jwt.secret-key=luuvietduongadminsmartrestaurant2026r1tpa36zu6sgvcdms8edi3r0z3x5yzqiCY72RXN54MBM840DEAVQ2BQHWZSZEZET
jwt.expiration=900000
refresh-token.expiration=30
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=smartrestaurant130907@gmail.com
spring.mail.password=zioilgspjdpemxde
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true




